//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePractice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonitoringSystemDBEntities : DbContext
    {
        public MonitoringSystemDBEntities()
            : base("name=MonitoringSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Категория_мероприятия> Категория_мероприятия { get; set; }
        public virtual DbSet<Категория_проблемы> Категория_проблемы { get; set; }
        public virtual DbSet<Мероприятия> Мероприятия { get; set; }
        public virtual DbSet<МКД> МКД { get; set; }
        public virtual DbSet<Обращения> Обращения { get; set; }
        public virtual DbSet<ОПФ_ук> ОПФ_ук { get; set; }
        public virtual DbSet<Сезон_обращения> Сезон_обращения { get; set; }
        public virtual DbSet<Состояние_дома> Состояние_дома { get; set; }
        public virtual DbSet<Способ_управления_МКД> Способ_управления_МКД { get; set; }
        public virtual DbSet<Статус_мероприятия> Статус_мероприятия { get; set; }
        public virtual DbSet<Статус_обращения> Статус_обращения { get; set; }
        public virtual DbSet<Тема_обращения> Тема_обращения { get; set; }
        public virtual DbSet<Тип_учётной_записи> Тип_учётной_записи { get; set; }
        public virtual DbSet<Управляющие_компании> Управляющие_компании { get; set; }
        public virtual DbSet<Учётные_записи> Учётные_записи { get; set; }
        public virtual DbSet<Фото> Фото { get; set; }
    }
}
