//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePractice
{
    using Microsoft.Office.Interop.Excel;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Управляющие_компании
    {
        public Управляющие_компании()
        {
            this.МКД = new HashSet<МКД>();
        }
    
        public int код_ук { get; set; }
        [Display(Name = "Название")]
        public string название { get; set; }
        [Display(Name = "Фирменное наименование")]
        public string фирм_наим { get; set; }
        [Display(Name = "Сокращённое наименование")]
        public string сокр_наим { get; set; }
        [Display(Name = "Руководитель")]
        public string ФИО_руков { get; set; }
        [Display(Name = "Дата получения лицензии")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> дата_получения_лицензии { get; set; }
        [Display(Name = "Номер лицензии")]
        public string номер_лицензии { get; set; }
        [Display(Name = "Орган, выдавший лицензию")]
        public string орган_выдавший_лицензию { get; set; }
        [Display(Name = "ИНН")]
        public string ИНН { get; set; }
        [Display(Name = "Организационно-правовая форма")]
        public Nullable<int> ОПФ { get; set; }
        [Display(Name = "ОГРН")]
        public string ОГРН { get; set; }
        [Display(Name = "Почтовый адрес")]
        public string почтовый_адрес { get; set; }
        [Display(Name = "Адрес фактического местонахождения органов управления")]
        public string адрес_ФМОУ { get; set; }
        [Display(Name = "Место государственной регистрации юр.лица")]
        public string место_ГРЮЛ { get; set; }
        [Display(Name = "Адрес диспетчерской службы")]
        public string адрес_дисп_службы { get; set; }
        [Display(Name = "Контактный телефон")]
        public string контактный_телефон { get; set; }
        [Display(Name = "Адрес электронной почты")]
        public string адрес_электронной_почты { get; set; }
        [Display(Name = "Учётная запись")]
        public int учётная_запись { get; set; }
        [Display(Name = "Подтверждение администратора сервиса")]
        public bool подтверждение { get; set; }
        public virtual ICollection<МКД> МКД { get; set; }
        public virtual ОПФ_ук ОПФ_ук { get; set; }
        public virtual Учётные_записи Учётные_записи { get; set; }
    }
}
