//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Учётные_записи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Учётные_записи()
        {
            this.Обращения = new HashSet<Обращения>();
            this.Управляющие_компании = new HashSet<Управляющие_компании>();
        }
    
        public int код_пользователя { get; set; }
        public string логин { get; set; }
        public string пароль { get; set; }
        public int тип_учётной_записи { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Обращения> Обращения { get; set; }
        public virtual Тип_учётной_записи Тип_учётной_записи1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Управляющие_компании> Управляющие_компании { get; set; }
    }
}
